### PR TITLE
Fix modifier key usage and probably issue #16.

### PR DESCRIPTION
**Pull request by nusgart**
Like @david-christiansen (issue #16), I had noticed that the keyboard would fail to work
seemingly at random, but found that the Abort key and the arrow keys would
insert characters, and backspace would delete them. Upon some debugging, I found
that numlock erroneously activates the meta modifier, so all key presses would
be treated as M-`key`, except for the keys handled specially in process_key (eg:
F1-F12, Backspace, ...).

The fix I implemented attempts to assign the meta and alt modifier masks based
on the keys assigned to each modifier, which prevents numlock from activating
meta -- note that the function of each modifier is not fixed even for a single
keyboard layout (eg: "US").

### CODE REVIEW

**Comment by ams** [comment]
Lovley, thank you!  Alas, I think I'll hold off just a tiny bit -- I'm currently reworking the keyboard code. 

Most notably, I would really like to be able to reassign keys from the configuration file.  E.g., being able to specify which bucky and modifiers map to in X11 (Meta -> XK_Meta_LR, Top -> XK_Alt_L/R).  But also being able to switch between a pure Knight and the more "sensible' Space Cadet layout -- since then we don't need the nasty remapping to US keys and could leave the Knight setup as it was originally.

Do you have any ideas on what the configuration file could look like?  What do you think about the above?

**Comment by nusgart** [comment]
I definitely think that the modifier key mapping is a good idea -- perhaps a comma delimited list in the ini file perhaps as a section along the lines of
```
[keymap]
meta_keys=XK_META_L,XK_META_R
```
It might also be a good idea to allow configuration of the Terminal, System, and other special keys.  However, I do think that the mapping between key codes and keysyms should probably be left to X11 (I'm not sure if that's what you were getting at with the Space Cadet vs Knight keyboard layout).  Overall, though, I really like the idea of configurable key bindings.

**Comment by ams** [comment]
The space cadet vs knight keyboard is rather that the knight keyboard did not have System/Terminal/... keys.  You had to press Top plus some other ones to get that.  The knight keyboard layout wasn’t entirely a US layout either, hence the ugly remapping going on in kbd.c.

**Comment by ams** [comment]
Decided that I might as well just merge, and rebase whatever hacks I am working.

**Comment by ams** [comment]
The num-lock issue is prolly also related to this line:

https://github.com/LM-3/usim/blob/a94ec1815100fc98aa77d84ebd9af17d82830dcc/kbd.c#L184

0x7f is basically XK_Num_Lock ...

**Comment by ams** [comment]
@nusgart I reworked the keyboard code, might be of interest to see that I didn't shaft it entierly...

**Comment by nusgart** [comment]
@ams, your changes seem good to me -- I completely forgot about super (although I thought that it was a separate key from top, or is that just on the space-cadet keyboards), and the new constant definitions make the code easier to understand to someone who hasn't read the keyboard section of the CADR manual.

**Comment by ams** [comment]
That is indeed correct! Super (and Hyper) are Cadet keys, much like System though that was done via Top-Escape on the Knight keyboard.  I don't think you could input Hyper/Super/... via the Knight keyboard.

**Pull request merged**
